XionIT/Controllers/PeopleController.cs
using XionIT.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace XionIT.Controllers
{
	[Authorize(Roles = @"Admin")]
	public class PeopleController : BaseController
	{
		public PeopleController()
		{
		}

		public PeopleController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
			: base(userManager, roleManager)
		{
		}

		//
		// GET: /People/
		public async Task<ActionResult> Index()
		{
			var model = new List<IndexPeopleViewModel>();
			var users = await UserManager.Users.ToListAsync();

			foreach (var user in users)
			{
				model.Add(new IndexPeopleViewModel()
				{
					Id = user.Id,
					Name = user.UserName,
					Email = user.Email,
					Created = user.Created,
					NumberOfAssets = user.Assets.Count(),
					Roles = string.Join(", ", await UserManager.GetRolesAsync(user.Id))
				});
			}


			return View(model);
		}

		//
		// GET: /People/Details/5
		public async Task<ActionResult> Details(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var user = await UserManager.FindByIdAsync(id);

			ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

			return View(user);
		}

		//
		// GET: /People/Create
		public async Task<ActionResult> Create()
		{
			//Get the list of Roles
			ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
			return View();
		}

		//
		// POST: /People/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(NewPersonViewModel userViewModel) //, params string[] selectedRoles)
		{
			if (ModelState.IsValid)
			{
				var now = DateTime.UtcNow;
				var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email, Created = now, Updated = now };

				// Admins only get passwords to login
				IdentityResult adminresult = null;

				if (userViewModel.Roles.Contains(@"Admin", StringComparer.InvariantCultureIgnoreCase))
					adminresult = await UserManager.CreateAsync(user, userViewModel.Password);
				else
					adminresult = await UserManager.CreateAsync(user); // Not Admin, doesn't need a password.

				//Add User to the selected Roles 
				if (adminresult.Succeeded)
				{
					if (userViewModel.Roles != null)
					{
						var result = await UserManager.AddToRolesAsync(user.Id, userViewModel.Roles);
						if (!result.Succeeded)
						{
							ModelState.AddModelError("", result.Errors.First());
							ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
							return View();
						}
					}
				}
				else
				{
					ModelState.AddModelError("", adminresult.Errors.First());
					ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
					return View();

				}

				SetRedirectSuccess(@"User created.");
				return RedirectToAction("Index");
			}
			ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
			return View();
		}

		//
		// GET: /People/Edit/1
		public async Task<ActionResult> Edit(string id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var user = await UserManager.FindByIdAsync(id);
			if (user == null)
				return HttpNotFound();

			var userRoles = await UserManager.GetRolesAsync(user.Id);
			ViewBag.Roles = new SelectList(RoleManager.Roles, "Name", "Name");

			ViewBag.AllAssets = await GetAssetSelectListAsync();

			var model = new EditUserViewModel()
			{
				Id = user.Id,
				Email = user.Email,
				SelectedRole = userRoles.FirstOrDefault(),
				AssignedAssetIds = user.Assets.Select(x => x.Id).ToList(),
			};

			return View(model);
		}

		//
		// POST: /People/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(EditUserViewModel editUser)
		{
			ViewBag.Roles = new SelectList(RoleManager.Roles, "Name", "Name");
			ViewBag.AllAssets = await GetAssetSelectListAsync();

			if (ModelState.IsValid)
			{
				try
				{
					var user = await UserManager.FindByIdAsync(editUser.Id);
					if (user == null)
						return HttpNotFound();

					// Roles.
					var userRoles = await UserManager.GetRolesAsync(user.Id);
					var editUserRoles = new string[] { };

					if (!string.IsNullOrEmpty(editUser.SelectedRole))
						editUserRoles = new string[] { editUser.SelectedRole };

					// Roles. Add to new roles
					var result = await UserManager.AddToRolesAsync(user.Id, editUserRoles.Except(userRoles).ToArray());
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(editUser);
					}

					// Roles. Remove from roles
					result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(editUserRoles).ToArray());
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(editUser);
					}

					// Assets.
					var selectedAssets = new List<Asset>();
					if (editUser.AssignedAssetIds != null && editUser.AssignedAssetIds.Any())
						selectedAssets = AppDbContext.Assets.Where(x => editUser.AssignedAssetIds.Contains(x.Id)).ToList();

					// Assets. clear/add new assets
					user.Assets.Clear();
					selectedAssets.ForEach(x => user.Assets.Add(x));

					// Passwords. Only if they provided one
					if (!string.IsNullOrEmpty(editUser.NewPassword)
						&& !string.IsNullOrEmpty(editUser.ConfirmPassword))
					{
						// obviously must match
						if (!editUser.NewPassword.Equals(editUser.ConfirmPassword))
						{
							ModelState.AddModelError("", @"New password doesn't match confirmation password.");
							return View(editUser);
						}

						// If the user has an existing password, lets change it (and verify their current one)
						if (await UserManager.HasPasswordAsync(user.Id))
						{
							result = await UserManager.ChangePasswordAsync(user.Id, editUser.CurrentPassword, editUser.NewPassword);
							if (!result.Succeeded)
							{
								ModelState.AddModelError("", result.Errors.First());
								return View(editUser);
							}
						}
						// If the user doesn't have a password, lets just add it
						else
						{
							result = await UserManager.AddPasswordAsync(user.Id, editUser.NewPassword);
							if (!result.Succeeded)
							{
								ModelState.AddModelError("", result.Errors.First());
								return View(editUser);
							}
						}
					}

					await AppDbContext.SaveChangesAsync();

					SetRedirectSuccess(@"Updated Successfully!");
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.ToString());
					return View(editUser);
				}
			}
			ModelState.AddModelError("", "Something failed.");
			return View(editUser);
		}

		//
		// GET: /People/Delete/5
		public async Task<ActionResult> Delete(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var user = await UserManager.FindByIdAsync(id);
			if (user == null)
			{
				return HttpNotFound();
			}

			var model = new DeletePeopleViewModel() {
				Id = user.Id,
				Username = user.UserName,
				NumAssets = user.Assets.Count(),
				Delete = false
			};

			return View(model);
		}

		//
		// POST: /People/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteConfirmed(DeletePeopleViewModel model)
		{
			if (ModelState.IsValid)
			{
				try
				{
					if (model.Id == null)
						return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

					if (!model.Delete)
					{
						SetRedirectInfo(@"Person was not deleted.");
						return RedirectToAction("index");
					}

					var user = await UserManager.FindByIdAsync(model.Id);
					if (user == null)
						return HttpNotFound();

					var result = await UserManager.DeleteAsync(user);
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(model);
					}

					SetRedirectSuccess(@"Person deleted!");
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(@"", ex.ToString());
					return View(model);
				}
			}
			return View(model);
		}
	}
}

XionIT/Controllers/SiteMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using XionIT.Models;

namespace XionIT.Controllers
{
	public class SiteMapController : BaseController
	{
		// GET: SiteMap
		public ActionResult Index()
		{
			var sitemapItems = new List<SitemapItem>();
			var map = GetSiteMap();

			foreach (var x in map)
			{
				sitemapItems.Add(new SitemapItem(Url.QualifiedAction(x.Action, x.Controller)));
				foreach (var child in x.Children) // Single level, i don't have crazy pages.
					sitemapItems.Add(new SitemapItem(Url.QualifiedAction(child.Action, child.Controller)));
			}

			return new SitemapResult(sitemapItems);
		}

		public ActionResult Human()
		{
			var map = GetSiteMap();

			return View(map);
		}

		IList<MapItem> GetSiteMap()
		{
			var map = new List<MapItem>() {
				MapItem.Create(@"index", @"home", "Home Page").AddChild("about").AddChild("contact"),
				MapItem.Create(@"index", "dashboard", "Dashboard", true),
				MapItem.Create(@"index", "people", "People", true).AddChild("details", hasParams:true).AddChild("create").AddChild("edit", hasParams:true).AddChild("delete", hasParams:true),
				MapItem.Create(@"index", "assets", "Assets", true).AddChild("details", hasParams:true).AddChild("create").AddChild("edit", hasParams:true).AddChild("delete", hasParams:true),
				MapItem.Create(@"index", "reports", "Reports", true).AddChild("asset", hasParams:true).AddChild("person", hasParams:true),
				MapItem.Create(@"index", "manage", "Account Management", true).AddChild("setpassword", name:"Set Password").AddChild("changepassword", name:"Change Password"),
				MapItem.Create(@"index", "account", "Login Managment").AddChild("login").AddChild("register"),
				MapItem.Create(@"index", "sitemap", "Site Map").AddChild("human")
			};
			return map;
		}


	}

}

XionIT/Views/Shared/_Footer.cshtml
<footer>
	<hr />
	<div class="row">
		<div class="col-md-12 text-center">
			<p>Xion IT Asset Management | <small>Richard Shaw (@DateTime.Now.Year)</small></p>
			<ul class="list-inline hidden-print">
				<li><a href="@Url.Action("about", "Home")">About Us</a></li>
				<li><a href="@Url.Action("contact", "Home")">Contact Us</a></li>
				<li><a href="@Url.Action("human", "SiteMap")">Site Map</a></li>
			</ul>
		</div>
	</div>
</footer>

XionIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@RenderSection("styles", required: false)
	@Scripts.Render("~/bundles/modernizr")

</head>
<body>

	@Html.Partial("_Navigation")

	<div class="container body-content">
		@Html.Partial("_PageTitle")
		@Html.Partial("_PageMessage")
		@RenderBody()
	</div>

	<div class="container">
		@Html.Partial("_Footer")
	</div>

	

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/sitejs")
	@RenderSection("scripts", required: false)

</body>
</html>

XionIT/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNet.Identity

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">

			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			@Html.ActionLink("Xion IT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

		</div>

		<div class="navbar-collapse collapse">

			<ul class="nav navbar-nav">

				@if (Request.IsAuthenticated)
				{
					<li class="@Html.IsSelected("Index", "Dashboard")">@Html.ActionLink("Dashboard", "index", "Dashboard")</li>

					<li class="dropdown @Html.IsSelected(controller: "Users")">
						<a href="@Url.Action("index", "People")" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">People <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li>@Html.ActionLink("All People", "index", "People")</li>
							<li>@Html.ActionLink("New Person", "create", "People")</li>
						</ul>
					</li>

					<li class="dropdown @Html.IsSelected(controller: "Assets")">
						<a href="@Url.Action("index", "Assets")" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Assets <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li>@Html.ActionLink("All Assets", "index", "Assets")</li>
							<li>@Html.ActionLink("New Asset", "create", "Assets")</li>
						</ul>
					</li>

					<li class="@Html.IsSelected("Index", "Reports")">@Html.ActionLink("Reports", "index", "Reports")</li>
				}

				<li class="@Html.IsSelected("About", "Home")">@Html.ActionLink("About", "About", "Home")</li>
				<li class="@Html.IsSelected("Contact", "Home")">@Html.ActionLink("Contact", "Contact", "Home")</li>
			</ul>

			@Html.Partial("_LoginPartial")

		</div>

	</div>

</div>

XionIT/Views/Shared/_PageMessage.cshtml
@if (ViewBag.Error != null)
{ 
	<div class="alert alert-dismissible alert-danger">
		<button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>
		<h4>An error has occurred!</h4>
		<p>@ViewBag.Error</p>
	</div>
}
@if (ViewBag.Warning != null)
{ 
	<div class="alert alert-dismissible alert-warning">
		<button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>
		<h4>Warning!</h4>
		<p>@ViewBag.Warning</p>
	</div>
}
@if (ViewBag.Info != null)
{ 
	<div class="alert alert-dismissible alert-info">
		<button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>
		<h4>Heads up!</h4>
		<p>@ViewBag.Info</p>
	</div>
}
@if (ViewBag.Success != null)
{ 
	<div class="alert alert-dismissible alert-success">
		<button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button>
		<h4>Success!</h4>
		<p>@ViewBag.Success</p>
	</div>
}

XionIT/Views/Shared/_PageTitle.cshtml
@{ 
	var pageTitle = ViewBag.Title ?? "";
	var pageSubTitle = ViewBag.SubTitle ?? "";
}

<h2>@pageTitle</h2>

@if(!string.IsNullOrEmpty(pageSubTitle))
{
	<h4>@pageSubTitle</h4>
}

<hr/>