XionIT/Models/AssetsViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace XionIT.Models
{
	public class CreateAssetViewModel
	{
		[Required]
		public string Name { get; set; }

		public string AssetModel { get; set; }

		public string Serialnumber { get; set; }

		public string AssetTag { get; set; }

		public string Description { get; set; }

		public string Notes { get; set; }

		public ICollection<string> SelectedUsers { get; set; }

		public CreateAssetViewModel()
		{
			SelectedUsers = new HashSet<string>();
		}

		public CreateAssetViewModel(Asset asset)
			:this()
		{

			Name = asset.Name;
			AssetModel = asset.Model;
			Serialnumber = asset.Serialnumber;
			AssetTag = asset.AssetTag;
			Description = asset.Description;
			Notes = asset.Notes;
			SelectedUsers = asset.Users.Select(x => x.Id).ToList();
		}
	}

	public class EditAssetViewModel : CreateAssetViewModel
	{
		[Required]
		public int AssetId { get; set; }

		public EditAssetViewModel()
			:base()
		{

		}

		public EditAssetViewModel(Asset asset)
			:base(asset)
		{
			AssetId = asset.Id;
		}

		public void UpdateAssetAsync(Asset asset, ICollection<ApplicationUser> users)
		{
			if (asset == null || users == null) return;

			asset.Name = Name;
			asset.Model = AssetModel;
			asset.Serialnumber = Serialnumber;
			asset.AssetTag = AssetTag;
			asset.Description = Description;
			asset.Notes = Notes;

			asset.Users.Clear();
			foreach (var userId in SelectedUsers)
			{
				var appUser = users.FirstOrDefault(x => x.Id == userId);
				if (appUser != null)
					asset.Users.Add(appUser);
			}

		}

	}

	public class DeleteAssetViewModel : EditAssetViewModel
	{
		public bool Delete { get; set; }

		public DeleteAssetViewModel()
			:base()
		{

		}

		public DeleteAssetViewModel(Asset asset)
			:base(asset)
		{

		}

	}

}

XionIT/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using XionIT.Models;
using System.Data.Entity;

namespace XionIT.Controllers
{
	[Authorize(Roles = @"Admin")]
	public class AssetsController : BaseController
    {
        // GET: Assets
        public async Task<ActionResult> Index()
        {
			var model = await AppDbContext.Assets.ToListAsync();
			return View(model);
        }


		public async Task<ActionResult> Create()
		{
			var allusers = await UserManager.Users.ToListAsync();
			ViewBag.Users = new SelectList(allusers, "Id", "Email");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(CreateAssetViewModel model)
		{
			var allusers = await UserManager.Users.ToListAsync();
			ViewBag.Users = new SelectList(allusers, "Id", "Email");

			if (ModelState.IsValid)
			{
				// If we use "right now" more than once
				var now = DateTime.UtcNow;
				
				try
				{
					// Create the new asset based off the view model
					var newAsset = new Asset()
					{
						Name = model.Name,
						Model = model.AssetModel,
						Serialnumber = model.Serialnumber,
						AssetTag = model.AssetTag,
						Description = model.Description,
						Notes = model.Notes,
						Created = now,
					};
					
					// For each selected user, assign them to this asset (and they will be assigned this asset)
					foreach (var userId in model.SelectedUsers)
					{
						var appUser = allusers.FirstOrDefault(x => x.Id == userId);
						if (appUser != null)
							newAsset.Users.Add(appUser);
					}

					// Add the new asset to the DBContext
					AppDbContext.Assets.Add(newAsset);

					// Save those changes
					await AppDbContext.SaveChangesAsync();
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(@"", ex.ToString());
					return View();
				}

				SetRedirectSuccess(@"Asset created.");
				return RedirectToAction("Index");
			}

			return View();
		}
		
		public async Task<ActionResult> Details(int id)
		{
			var asset = await AppDbContext.Assets.FirstOrDefaultAsync(x => x.Id == id);

			if (asset == null)
				return new RedirectWithErrorResult("index", "Unknown or missing asset.");

			return View(asset);
		}

		public async Task<ActionResult> Edit(int id)
		{
			var asset = await AppDbContext.Assets.FirstOrDefaultAsync(x => x.Id == id);

			if (asset == null)
				return new RedirectWithErrorResult("index", "Unknown or missing asset.");

			var model = new EditAssetViewModel(asset);

			var allusers = await UserManager.Users.ToListAsync();
			ViewBag.Users = new SelectList(allusers, "Id", "Email");

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(EditAssetViewModel editModel)
		{
			var allusers = await UserManager.Users.ToListAsync();
			ViewBag.Users = new SelectList(allusers, "Id", "Email");

			try
			{
				if (ModelState.IsValid)
				{
					var asset = await AppDbContext.Assets.FirstOrDefaultAsync(x => x.Id == editModel.AssetId);
					if (asset == null)
						return new RedirectWithErrorResult("index", "Unknown or missing asset.");

					editModel.UpdateAssetAsync(asset, allusers);

					await AppDbContext.SaveChangesAsync();

					SetRedirectSuccess(@"Asset was updated.");
					return RedirectToAction(@"index");
				}
			}
			catch (Exception ex)
			{
				SetRedirectError(ex.ToString());
			}

			return View(editModel);
		}

		public async Task<ActionResult> Delete(int id)
		{
			var asset = await AppDbContext.Assets.FirstOrDefaultAsync(x => x.Id == id);

			if (asset == null)
				return new RedirectWithErrorResult("index", "Unknown or missing asset.");

			var model = new DeleteAssetViewModel(asset);

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(DeleteAssetViewModel model)
		{
			var asset = await AppDbContext.Assets.FirstOrDefaultAsync(x => x.Id == model.AssetId);

			if (asset == null)
				return new RedirectWithErrorResult("index", "Unknown or missing asset.");

			if(!model.Delete)
			{
				SetRedirectInfo(@"Asset was not deleted.");
				return RedirectToAction("index");
			}


			try
			{
				AppDbContext.Assets.Remove(asset);

				await AppDbContext.SaveChangesAsync();

				SetRedirectSuccess(@"Asset deleted!");
				return RedirectToAction("index");
			}
			catch (Exception ex)
			{
				SetRedirectError(ex.ToString());
			}

			return View(model);
		}


    }
}

XionIT/Controllers/PeopleController.cs
using XionIT.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace XionIT.Controllers
{
	[Authorize(Roles = @"Admin")]
	public class PeopleController : BaseController
	{
		public PeopleController()
		{
		}

		public PeopleController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
			: base(userManager, roleManager)
		{
		}

		//
		// GET: /People/
		public async Task<ActionResult> Index()
		{
			var model = new List<IndexPeopleViewModel>();
			var users = await UserManager.Users.ToListAsync();

			foreach (var user in users)
			{
				model.Add(new IndexPeopleViewModel()
				{
					Id = user.Id,
					Name = user.UserName,
					Email = user.Email,
					Created = user.Created,
					NumberOfAssets = user.Assets.Count(),
					Roles = string.Join(", ", await UserManager.GetRolesAsync(user.Id))
				});
			}


			return View(model);
		}

		//
		// GET: /People/Details/5
		public async Task<ActionResult> Details(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var user = await UserManager.FindByIdAsync(id);

			ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

			return View(user);
		}

		//
		// GET: /People/Create
		public async Task<ActionResult> Create()
		{
			//Get the list of Roles
			ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
			return View();
		}

		//
		// POST: /People/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create(NewPersonViewModel userViewModel) //, params string[] selectedRoles)
		{
			if (ModelState.IsValid)
			{
				var now = DateTime.UtcNow;
				var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email, Created = now, Updated = now };

				// Admins only get passwords to login
				IdentityResult adminresult = null;

				if (userViewModel.Roles.Contains(@"Admin", StringComparer.InvariantCultureIgnoreCase))
					adminresult = await UserManager.CreateAsync(user, userViewModel.Password);
				else
					adminresult = await UserManager.CreateAsync(user); // Not Admin, doesn't need a password.

				//Add User to the selected Roles 
				if (adminresult.Succeeded)
				{
					if (userViewModel.Roles != null)
					{
						var result = await UserManager.AddToRolesAsync(user.Id, userViewModel.Roles);
						if (!result.Succeeded)
						{
							ModelState.AddModelError("", result.Errors.First());
							ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
							return View();
						}
					}
				}
				else
				{
					ModelState.AddModelError("", adminresult.Errors.First());
					ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
					return View();

				}

				SetRedirectSuccess(@"User created.");
				return RedirectToAction("Index");
			}
			ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
			return View();
		}

		//
		// GET: /People/Edit/1
		public async Task<ActionResult> Edit(string id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			var user = await UserManager.FindByIdAsync(id);
			if (user == null)
				return HttpNotFound();

			var userRoles = await UserManager.GetRolesAsync(user.Id);
			ViewBag.Roles = new SelectList(RoleManager.Roles, "Name", "Name");

			ViewBag.AllAssets = await GetAssetSelectListAsync();

			var model = new EditUserViewModel()
			{
				Id = user.Id,
				Email = user.Email,
				SelectedRole = userRoles.FirstOrDefault(),
				AssignedAssetIds = user.Assets.Select(x => x.Id).ToList(),
			};

			return View(model);
		}

		//
		// POST: /People/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit(EditUserViewModel editUser)
		{
			ViewBag.Roles = new SelectList(RoleManager.Roles, "Name", "Name");
			ViewBag.AllAssets = await GetAssetSelectListAsync();

			if (ModelState.IsValid)
			{
				try
				{
					var user = await UserManager.FindByIdAsync(editUser.Id);
					if (user == null)
						return HttpNotFound();

					// Roles.
					var userRoles = await UserManager.GetRolesAsync(user.Id);
					var editUserRoles = new string[] { };

					if (!string.IsNullOrEmpty(editUser.SelectedRole))
						editUserRoles = new string[] { editUser.SelectedRole };

					// Roles. Add to new roles
					var result = await UserManager.AddToRolesAsync(user.Id, editUserRoles.Except(userRoles).ToArray());
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(editUser);
					}

					// Roles. Remove from roles
					result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(editUserRoles).ToArray());
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(editUser);
					}

					// Assets.
					var selectedAssets = new List<Asset>();
					if (editUser.AssignedAssetIds != null && editUser.AssignedAssetIds.Any())
						selectedAssets = AppDbContext.Assets.Where(x => editUser.AssignedAssetIds.Contains(x.Id)).ToList();

					// Assets. clear/add new assets
					user.Assets.Clear();
					selectedAssets.ForEach(x => user.Assets.Add(x));

					// Passwords. Only if they provided one
					if (!string.IsNullOrEmpty(editUser.NewPassword)
						&& !string.IsNullOrEmpty(editUser.ConfirmPassword))
					{
						// obviously must match
						if (!editUser.NewPassword.Equals(editUser.ConfirmPassword))
						{
							ModelState.AddModelError("", @"New password doesn't match confirmation password.");
							return View(editUser);
						}

						// If the user has an existing password, lets change it (and verify their current one)
						if (await UserManager.HasPasswordAsync(user.Id))
						{
							result = await UserManager.ChangePasswordAsync(user.Id, editUser.CurrentPassword, editUser.NewPassword);
							if (!result.Succeeded)
							{
								ModelState.AddModelError("", result.Errors.First());
								return View(editUser);
							}
						}
						// If the user doesn't have a password, lets just add it
						else
						{
							result = await UserManager.AddPasswordAsync(user.Id, editUser.NewPassword);
							if (!result.Succeeded)
							{
								ModelState.AddModelError("", result.Errors.First());
								return View(editUser);
							}
						}
					}

					await AppDbContext.SaveChangesAsync();

					SetRedirectSuccess(@"Updated Successfully!");
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.ToString());
					return View(editUser);
				}
			}
			ModelState.AddModelError("", "Something failed.");
			return View(editUser);
		}

		//
		// GET: /People/Delete/5
		public async Task<ActionResult> Delete(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var user = await UserManager.FindByIdAsync(id);
			if (user == null)
			{
				return HttpNotFound();
			}

			var model = new DeletePeopleViewModel() {
				Id = user.Id,
				Username = user.UserName,
				NumAssets = user.Assets.Count(),
				Delete = false
			};

			return View(model);
		}

		//
		// POST: /People/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteConfirmed(DeletePeopleViewModel model)
		{
			if (ModelState.IsValid)
			{
				try
				{
					if (model.Id == null)
						return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

					if (!model.Delete)
					{
						SetRedirectInfo(@"Person was not deleted.");
						return RedirectToAction("index");
					}

					var user = await UserManager.FindByIdAsync(model.Id);
					if (user == null)
						return HttpNotFound();

					var result = await UserManager.DeleteAsync(user);
					if (!result.Succeeded)
					{
						ModelState.AddModelError("", result.Errors.First());
						return View(model);
					}

					SetRedirectSuccess(@"Person deleted!");
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError(@"", ex.ToString());
					return View(model);
				}
			}
			return View(model);
		}
	}
}

XionIT/Views/Assets/Create.cshtml
@using XionIT.Models;
@model  CreateAssetViewModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssetModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssetModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Serialnumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Serialnumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serialnumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssetTag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssetTag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssetTag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedUsers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.SelectedUsers, (SelectList)ViewBag.Users, null, new { @class = "form-control", multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.SelectedUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
				<a href="@Url.Action("index")" class="btn btn-default">Cancel</a>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Styles {
	@Styles.Render("~/Content/select2");
}

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/plugins/select2");
	<script>
		(function(){
			$('#SelectedUsers').select2({
				placeholder : "Select users"
			});
		})();
	</script>
}

XionIT/Views/Assets/Delete.cshtml
@using XionIT.Models;
@model DeleteAssetViewModel

@{
	ViewBag.Title = "Are you sure you want to delete this?";
}
<div>

	@Html.ValidationSummary(true, "", new { @class = "text-danger" })

	<dl class="dl-horizontal">

		<dt>
			@Html.DisplayNameFor(model => model.AssetId)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.AssetId)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.AssetModel)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.AssetModel)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Serialnumber)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Serialnumber)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.AssetTag)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.AssetTag)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Notes)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Notes)
		</dd>



	</dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

		@Html.HiddenFor(x => x.AssetId);

		<div class="checkbox">
			<label class="text-danger">
				@Html.CheckBoxFor(x => x.Delete) I understand that this is a irreversable action
			</label>
		</div>

		<div class="btn-group">
			<a href="@Url.Action(@"index")" class="btn btn-default">Cancel</a>
			<input type="submit" value="Delete" class="btn btn-danger" />
		</div>
		
	}
</div>

XionIT/Views/Assets/Details.cshtml
@using XionIT.Models;
@model Asset

@{
	ViewBag.Title = string.Format("{0} Details", Model.Name);
}

<div class="row">

	<div class="col-md-6">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Details</h3>
			</div>
			<table class="table table-condensed">
				<tr><th>@Html.DisplayNameFor(x => x.Id)</th><td>@Model.Id</td></tr>
				<tr><th>@Html.DisplayNameFor(x => x.Name)</th><td>@Model.Name</td></tr>
				<tr><th>@Html.DisplayNameFor(x => x.Model)</th><td>@Model.Model</td></tr>
				<tr><th>@Html.DisplayNameFor(x => x.Serialnumber)</th><td>@Model.Serialnumber</td></tr>
				<tr><th>@Html.DisplayNameFor(x => x.AssetTag)</th><td>@Model.AssetTag</td></tr>
			</table>
		</div>

	</div>

	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Assigned Users</h3>
			</div>
			<table class="table">
				<thead>
					<tr><th>User</th><th>Assigned Assets</th><th>Actions</th></tr>
				</thead>
				<tbody>
					@foreach (var user in Model.Users)
					{
						<tr>
							<td>@user.UserName</td>
							<td>@user.Assets.Count()</td>
							<td><a href="@Url.Action("details", "People", new { id = user.Id })">Details</a></td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>

</div>

<hr />

<div class="panel-group">

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">@Html.DisplayNameFor(x => x.Description)</h3>
		</div>
		<div class="panel-body">
			<p>@Model.Description</p>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">@Html.DisplayNameFor(x => x.Notes)</h3>
		</div>
		<div class="panel-body">
			<p>@Model.Notes</p>
		</div>
	</div>

</div>

<hr/>
<div class="pull-right">
	<a href="@Url.Action("index")" class="btn btn-default">Back</a>
	<a href="@Url.Action("edit", "Assets", new { id = Model.Id })" class="btn btn-warning">Edit</a>
</div>

XionIT/Views/Assets/Edit.cshtml
@using XionIT.Models;
@model EditAssetViewModel

@{
	ViewBag.Title = string.Format("Editing {0}", Model.Name);
}

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">

		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AssetModel, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AssetModel, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AssetModel, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Serialnumber, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Serialnumber, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Serialnumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AssetTag, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.AssetTag, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.AssetTag, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.SelectedUsers, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.ListBoxFor(model => model.SelectedUsers, (SelectList)ViewBag.Users, new { @class = "form-control", multiple = "multiple" })
				@Html.ValidationMessageFor(model => model.SelectedUsers, "", new { @class = "text-danger" })
			</div>
		</div>

		@Html.HiddenFor(model => model.AssetId)

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<a href="@Url.Action("index")" class="btn btn-default">Cancel</a>
				<input type="submit" value="Update" class="btn btn-primary" />
			</div>
		</div>
	</div>
}

@section Styles {
	@Styles.Render("~/Content/select2");
}

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/plugins/select2");
	<script>
		(function(){

			$('#SelectedUsers').select2({placeholder : "Select users"});

		})();
	</script>

}